[[pages]]
path = "/"
screenshotTimestamp = "2026-06-07T21:09:24Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/PgjOVbW"

[[pages]]
path = "/services"
screenshotTimestamp = "2026-06-07T21:02:37Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/2UhH0Nc"

[[pages]]
path = "/about"
screenshotTimestamp = "2026-06-07T20:34:46Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/gtQG4GK"

[[pages]]
path = "/portfolio"
screenshotTimestamp = "2026-06-07T20:34:57Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/eidsEXU"

[[pages]]
path = "/contact"
screenshotTimestamp = "2026-06-07T20:35:00Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/rZJEUzy"

[[pages]]
path = "/book-call"
screenshotTimestamp = "2026-06-07T21:02:34Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/jr5WPMF"

[[pages]]
path = "/admin"
screenshotTimestamp = "2026-06-08T06:46:01Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/c60b4022-6e3c-4459-9d93-341caeda4fd9/434d1131-0504-41cc-afdc-f0a23dad827a/fTHyhL3"
