kind = "web"
previewPath = "/"
title = "TheHexaSystem"
version = "1.0.0"
id = "artifacts/hexasystem"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19777

[services.development]
run = "pnpm --filter @workspace/hexasystem run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hexasystem", "run", "build" ]
publicDir = "artifacts/hexasystem/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19777"
BASE_PATH = "/"
